### ISSUE TITLE
Documentation in this repo, or main Hypha repo?

### ISSUE THREAD

**Issue by maxpearl** [HyphaApp/hypha-docs#2]
From Hypha Summit:

**Should documentation be in same repository as code?**

- Pros:
  - When one makes a code change that implies a doc change, the doc changes can take place in the same commit(s).
  - One only has to clone one repository to get both code and docs.
  - Having them in the same place encourages devs to become doc contributors as well.
- Cons:
  - ?

**Comment by frjo** [comment]
I prefer to have the documentation in a separate repository like now.

* Direct commits to main branch  is not allowed on the code repo, all changes must be done in feature branches and have issues and pull requests. The document repository can be more lax with this and move faster I believe.
* Most of the documentation will be written by other people than the code.

**Comment by emlini** [comment]
Adding to the con: 
- Folks unfamiliar with the dev side of things (or coding in general) may be overwhelmed trying to navigate the code repo in order to access/edit/request changes to documentation

I agree with the pros you identified, @maxpearl, though I see them as issues to be resolved.  I'll put some thoughts about each here, but we might want to open up separate issues for them to allow for more contributions/suggestions about how to resolve/alleviate:

1. I agree that there needs to be a system for communicating when a code change that implies a doc change is made, so doc writers are informed and can make appropriate changes - perhaps when resolving issues, the resolver can tag doc writers to indicate that a doc change is needed?
2. I think we could *link the documentation repo* somewhere in the code repo (maybe the README) to make it easier for folks to access
3. What I'm hearing from @frjo's comment is low confidence that devs will *in practice* be contributing to documentation.  I think it's important for @maxpearl and I to identify why we think it's important for devs to be involved in doc writing, then maybe we as doc writers can meet/chat with devs to get input/feedback on documentation.

**Comment by maxpearl** [comment]
I do kinda agree with @frjo's comment that much of the doc writing won't be done by devs - I don't know how realistic an expectation it is to have them write especially end-user docs. And I also agree with the con that the documentation can move faster if it's separate. I'm fine with it being separate.

@kfogel suggested this idea, so he might have a comment here.

I think having devs tag doc writers when an issue is closed is a great idea - @frjo is that realistic?

**Comment by frjo** [comment]
@maxpearl Tagging issues needing new or updated documentation is a good idea I think. I have added a label for that purpose, https://github.com/HyphaApp/hypha/labels/Type%3A%20Need%20documentation.

**Comment by kfogel** [comment]
If the code repository has a gated `main` branch with rules that are more appropriate to code than to docs, then yes, I agree, docs in a separate repository makes more sense, for all the reasons explained above.

**Comment by maxpearl** [comment]
OK, the consensus is to have the docs remain in a separate repository.
