### ISSUE TITLE
"Contributors" vs "Contributing" in the Hypha documentation.

### ISSUE THREAD

**Issue by kfogel** [HyphaApp/hypha-docs#48]
In [CONTRIBUTING.md](https://github.com/HyphaApp/hypha/blob/main/CONTRIBUTING.md) in the main Hypha source tree, we link to https://docs.hypha.app/contributing/ (twice, actually).

Currently, that's a dead link.  When I went to the [documentation site](https://docs.hypha.app/), I see that it has ".../contributors" rather than ".../contributing".  That is, https://docs.hypha.app/contributors works but https://docs.hypha.app/contributing does not (it gets a "Page Not Found" error).

Originally, my plan was to submit a doc PR here to turn "contributors" to "contributing", because the latter seems like a better path -- after all, the documentation is about how to contribute (i.e., about the verb), not about the particular personalities (the contributors) who do so.  And `contributing` is where Hypha's `CONTRIBUTING.md` file (note its name :-) ) already expects the documentation to be.

But then as I started to work on that PR, things got more confusing.  In the [documentation source tree](https://github.com/HyphaApp/hypha-docs), we already have *both* a `contributors/` folder and a `contributing/` folder.  I can't tell from looking at them what the difference between them is, but in any case clearly the latter one is currently inactive on the live docs site (although it does have one Markdown file there in the source tree).

So here is my proposal:

1) We consolidate all documentation under `contributing/`.  This includes *both* documentation about to contribute to Hypha itself and documentation about how to contribute to this documentation.
2) We leave forwarding pointers from all paths that currently exist under`contributors/`.
3) The one Markdown file currently located under `contributing/` will stay there.  We may later make a separate PR to more clearly separate Hypha documentation from Hypha-documentation documentation.

I am happy to submit a PR to do (1) and (2), if we agree on it.  Once that's done, we can evaluate (3).

(See also the [related thread in Hypha Discourse](https://we.hypha.app/t/contributors-vs-contributing-in-the-hypha-documentation-issue-48/379).)

**Comment by frjo** [comment]
I like these suggestions.

**Comment by Erioldoesdesign** [comment]
For context I think @emlini did have some in progress pages for the types people that contribute 'Contributors' as well as 'contributing' which is as you say the nuts and bolts of how to contribute.

But +1 to your suggestions. Would love to see a clear contributing.md someday as I remember those convos from earlier in the year being paused until governance was settled.

**Comment by fourthletter** [comment]
I updated information in [CONTRIBUTING.md](https://github.com/HyphaApp/hypha/blob/main/CONTRIBUTING.md) and consolidated the [documentation source tree](https://github.com/HyphaApp/hypha-docs). 

![Screenshot 2022-08-08 2 08 20 PM](https://user-images.githubusercontent.com/20019656/183418163-32b06820-8655-4410-bb79-1303328c6011.png)

Per your [suggestion](https://we.hypha.app/t/hypha-osss-repo-issues-quarterly-ish-triage-rebasing-grooming/339/8?u=dluong) last spring and in this issue, we are streamling the 'contribution' process for code, documentation, etc. We have been exploring some new approaches over the past few months: 

1. A more streamline platform for documentation like https://www.netlify.com/
2. Crafting clearer guidance on the type of documentation we need from adopters or end users
3. Building out technical documentation for developers

We will share the results of this work at the next adopters' meeting in September.

**Comment by kfogel** [comment]
Hey, thanks @Erioldoesdesign and @fourthletter.  A couple of questions:

@Erioldoesdesign I didn't quite understand the first sentence of your response -- were you saying that both "Contributors" and "Contributing" sections *should* be present, and that they are distinct in some way?

@fourthletter It looks like you've consolidated everything (yay!) under `contributors` in the doc tree.  I think `contributing` would be a better name for that -- just more natural for potential newcomers.  Would you be open to me submitting a PR to the doc tree to make that adjustment, and a similar PR to update CONTRIBUTING.md in the Hypha code tree accordingly?  (It seemed from his comment above that @frjo agrees with this course, as it was what I suggested in my original comment.)

**Comment by fourthletter** [comment]
Hi @kfogel - I changed the name to `contributing`  in the [doc tree](https://github.com/HyphaApp/hypha-docs/tree/main/contributing) and updated [CONTRIBUTING.md](https://github.com/HyphaApp/hypha/blob/main/CONTRIBUTING.md) with the correct urls. 

Thanks for taking the time to review the documentation and doc tree.

**Comment by emlini** [comment]
The "Contributors" page was from a time when we considered making all documentation categories **user-based** rather than **action-based** (see proposed organizational structure [here](https://docs.google.com/spreadsheets/d/1xtfnPa7xklQFHrfNNIyjYxWsQe7GwkQGe_ZNXIKaB58/edit#gid=739617997)).  The goal was to make documentation more accessible, and the proposed structure was generated with input from @Erioldoesdesign and @danblah, among others. 

I was working on updating the information architecture (see commits in February like [this one](url)), and shifting all existing documentation to the user-based categories.  I had actually edited the github repo fairly extensively (deleting the old action-based categories), but some conflicting updates (possibly a result of the Gitbook/Github linking process, or the different ways folks were editing documentation--github vs. Gitbook) reverted those changes.  I investigated at the time, but wasn't able to figure out why the structure kept reverting.

If it seems like folks are fine with the action-based categories, then we should definitely keep with the current structure.  Either way, I fully support streamlining documentation so we only have one or the other.

I also support the notion of using more streamlined documentation platform - I had proposed this several months ago, but not enough people were contributing to documentation other than me at the time to make it worth investigating further.

@fourthletter, re: your second point, I agree that we need more clarity on the types of documentation that would be useful **for** adopters and end-users.  I had been talking with adopters to determine the kinds of documentation that would be useful, and I had created some draft/full pages.  Some of those pages have since been deleted or content repurposed into other pages.  

Your post said "from" - were you suggesting that we need a contribution guide, other than [this one](https://github.com/HyphaApp/hypha-docs/blob/main/contributing/contribute-to-documentation.md)?
